"""phdtools.optimization.__init__.py

Copyright 2026 Marvin Meck

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import pandas as pd

from phdtools import DATA_DIR

from phdtools.data import (
    ISO_STD_REF_TEMPERATURE_SI,
    ISO_STD_REF_PRESSURE_SI,
    ISO_STD_REF_REL_HUMIDITY,
)
from phdtools.data.thermochemical import get_stdReactionEnthalpyFromKirchhoffsLaw


EPSILON = 1e-8

NUM_FINITE_ELEMENTS_REFORMER = 10
NUM_FINITE_ELEMENTS_SHIFT = 10

# Functional requirements
NOMINAL_THERMAL_POWER_SI = 12.5e3

FUEL_CELL_POWER_SI_LB = 300
FUEL_CELL_POWER_SI_UB = 1.0e3

# Design and operating parameters
THERMAL_EFFICIENCY_LB = 0.75
THERMAL_EFFICIENCY_UB = 1.0

FLOW_TEMPERATURE_HEATING_SI = 50 + 273.15
TERMINAL_TEMPERATURE_DIFFERENCE_SI = 5

NET_CALORIFIC_VALUE_METHANE_SI = get_stdReactionEnthalpyFromKirchhoffsLaw(
    ISO_STD_REF_TEMPERATURE_SI, reactions={"MCR2", "MCR1"}
)["MCR1"]
GROSS_CALORIFIC_VALUE_METHANE_SI = get_stdReactionEnthalpyFromKirchhoffsLaw(
    ISO_STD_REF_TEMPERATURE_SI, reactions={"MCR2", "MCR1"}
)["MCR2"]

OXYGEN_TO_CARBON_RATIO_LB = 1.5
OXYGEN_TO_CARBON_RATIO_UB = 2.5

REFORMER_STEAM_TO_CARBON_LB = 1.0
REFORMER_STEAM_TO_CARBON_UB = 3.0

REFORMER_TEMPERATURE_SI_LB = 800.0
REFORMER_TEMPERATURE_SI_UB = 1200.0
REFORMER_PRESSURE_SI = ISO_STD_REF_PRESSURE_SI
REFORMER_METHANE_CONVERSION_LB = 0.9

REFORMER_MASS_OF_SOLIDS_GRAM_LB = 0.1
REFORMER_MASS_OF_SOLIDS_GRAM_UB = 10.0

SHIFT_TEMPERATURE_SI_LB = 180 + 273.15
SHIFT_TEMPERATURE_SI_UB = 250 + 273.15
SHIFT_PRESSURE_SI = ISO_STD_REF_PRESSURE_SI

SHIFT_MASS_OF_SOLIDS_GRAM_LB = 10
SHIFT_MASS_OF_SOLIDS_GRAM_UB = 1e3

FUEL_CELL_TEMPERATURE_SI = 120 + 273.15
FUEL_CELL_PRESSURE_SI = ISO_STD_REF_PRESSURE_SI

FUEL_CELL_CARBON_MONOXIDE_TOLERANCE = 0.03

FUEL_CELL_TOTAL_ACTIVE_AREA_SI_LB = 50 * 1e-4
FUEL_CELL_TOTAL_ACTIVE_AREA_SI_UB = 2500 * 1e-4  # 3500 * 1e-4

# Cost modelling
REFORMER_BULK_DENSITY_CATALYST_SI = 1200
REFORMER_VOID_FRACTION_CATALYST_BED = 0.4
REFORMER_TUBE_DIAMETER_SI = 16e-3
REFORMER_TUBE_WALL_THICKNESS_SI = 1.2e-3

SHIFT_BULK_DENSITY_CATALYST_SI = 1300
SHIFT_VOID_FRACTION_CATALYST_BED = 0.4
SHIFT_TUBE_DIAMETER_SI = 16e-3
SHIFT_TUBE_WALL_THICKNESS_SI = 1.2e-3

FUEL_CELL_PRICE_EURO_PER_SQUARE_METER = 2000

INDIRECT_COSTS_EURO = 5000

CONTRIBUTION_MARGIN_LOWER_BOUND_EURO = 0
CONTRIBUTION_MARGIN_UPPER_BOUND_EURO = 14000

MARKUP_LOWER_BOUND = 1.5
MARKUP_UPPER_BOUND = 2.5

# Consumer preferences
INVESTMENT_TYPE = 0  # one-time payment
CONTRACT_DURATION_YEARS = 5
FEED_IN_TARIFF_EUR_PER_KWH = 0.08

GAS_PRICE_EUR_PER_KWH = 0.12
ELECTRICITY_PRICE_EUR_PER_KWH = 0.40
MATCHING_FACTOR = 0.5

REF_BOILER_EFFICIENCY = 0.9
THERMAL_EFFICIENCY_STATUS_QUO = (
    NET_CALORIFIC_VALUE_METHANE_SI
    / GROSS_CALORIFIC_VALUE_METHANE_SI
    * REF_BOILER_EFFICIENCY
)
CO2_EMISSION_FACTOR_GRAM_PER_KWH = 433

molarMassCarbonDioxideGramPerMol = pd.read_csv(
    DATA_DIR / "nist-webbook" / "critical-point.csv", index_col=0
)["M(g/mol)"]["C1O2(g)"]
CO2_EMISSION_FACTOR_MOL_PER_KWH = (
    CO2_EMISSION_FACTOR_GRAM_PER_KWH / molarMassCarbonDioxideGramPerMol
)

# Initial solution
REFORMER_TEMPERATURE_SI_INIT = REFORMER_TEMPERATURE_SI_UB
REFORMER_METHANE_CONVERSION_INIT = 0.9
REFORMER_STEAM_TO_CARBON_INIT = 2.0

SHIFT_TEMPERATURE_SI_INIT = SHIFT_TEMPERATURE_SI_UB

# TODO: remove this is an upper bound that depends on the value of the cost savings
# REF_MOLAR_FLOW_RATE_METHANE_IN_SI = -NOMINAL_THERMAL_POWER_SI / (REF_BOILER_EFFICIENCY * NET_CALORIFIC_VALUE_METHANE_SI)
